In [10]:
# Esta función devuelve una posible solución de forma vectorial
# no requiere ningún parámetro
import numpy as np
def suponerSolucion():
    base = np.array([6 , 4 ,  2 , 0 , 5 , 7 , 1 , 3])
    posibleSolucion = np.random.permutation(base)
    return posibleSolucion

In [11]:
#Esta función devuelve una matriz de 8filas por 8 columnas
#la función pinta la posible solución y el tablero de adjedrez con las 8 reinas.
#La función requiere el parámetro posibleSolución debe ser un array de 8 columnas con 1 fila
def construirTablero(posibleSolucion):
    tablero = np.zeros((8,8) , dtype= int)
    for i in range (len (posibleSolucion)):
        tablero[posibleSolucion[i]][i] = 1
    return tablero

In [12]:
#Esta función requiere el parámetro tablero, una matriz de 8x8 que contiene la posición de las reinas
#la función devuelve un diccionario de reinas para trabajar más cómoda la parte de las diagonales
def obtenerReinas(tablero):
    reinas = {}
    filas,columnas = np.where(tablero==1)
    for i in range(len(filas)):
        reinas[i] = np.array([filas[i], columnas[i]])
    return reinas
        

    

In [13]:
#Esta función sólo verifica si se cumple el criterio de las diagonales
#El parámetro de entrada es un diccionario que contiene las 8 reinas
def verificarDiagonales(diccionarioReinas):
    amenazaDiagonales = False
    for reinaActual in diccionarioReinas:
        for reinaAComparar in diccionarioReinas:
            if(reinaActual != reinaAComparar):
                filaActual,columnaActual = diccionarioReinas[reinaActual]
                filaComparar,columnaComparar = diccionarioReinas[reinaAComparar]
                condicion1 = (filaActual - columnaActual) == (filaComparar - columnaComparar)
                condicion2 = (filaActual + columnaActual) == (filaComparar + columnaComparar)
                condicion3 = (columnaActual - columnaComparar) == (filaActual - filaComparar)
                condicion4 = (columnaActual - columnaComparar) == (filaComparar - filaActual)
                if(condicion1 == True or condicion2 == True or condicion3 == True or condicion4 == True):
                    amenazaDiagonales = True;
                    break;
    return amenazaDiagonales

In [14]:
def encontrarSolucionesSinRepetir(soluciones):
    solucionesSinRepetir = []
    seRepite = False
    for i in range (len(soluciones)):
        for j in range (len (solucionesSinRepetir)):
            seRepite = np.all(soluciones[i] == solucionesSinRepetir[j])
            if (seRepite == True):
                break
        if (seRepite == False):
            solucionesSinRepetir.append(soluciones[i])
    return solucionesSinRepetir

In [15]:
#Esta función toma las soluciones y las imprime
def mostrarSoluciones(soluciones):
    print ("Existe un total de ", len(soluciones), " soluciones encontradas en la ejecución")
    j = 1
    for solucion in soluciones:
        print("*********************************************************************************")
        print("Esta es la solución ", j)
        print (solucion)
        j = j + 1
        print("*********************************************************************************")

## El problema de las ocho reinas.
En este notebook, planteamos una posible solución de código para hallar las 92 soluciones    
posibles al problema de ubicar 8 reinas en un tablero de adjedréz sin que ninguna de estas  
se amenacen.

In [16]:
#Este notebook es el que ejecuta todo 
soluciones = []
solucionesSinRepetir = []
J = 0
while ( len(solucionesSinRepetir) < 91 ):
    J = J + 1 
    posibleSolucion = suponerSolucion()
    tablero = construirTablero(posibleSolucion)
    reinas = obtenerReinas(tablero)
    amenazaDiagonales = verificarDiagonales(reinas)
    if( amenazaDiagonales == False ):
        tablero2 = np.rot90(tablero)
        tablero3 = np.rot90(tablero2)
        tablero4 = np.rot90(tablero3)
        soluciones.append(tablero)
        soluciones.append(tablero2)
        soluciones.append(tablero3)
        soluciones.append(tablero4)
        solucionesSinRepetir = encontrarSolucionesSinRepetir(soluciones)
print ("Se ejecutaron ",J, " pasos para hallar todas las soluciones")
mostrarSoluciones(solucionesSinRepetir)

Se ejecutaron  53481  pasos para hallar todas las soluciones
Existe un total de  92  soluciones encontradas en la ejecución
*********************************************************************************
Esta es la solución  1
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]
*********************************************************************************
*********************************************************************************
Esta es la solución  2
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]
*********************************************************************************
*********************************************************************************
Esta es la solución  3
[[0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0

In [17]:
#Este notebook se encarga de mostrar las soluciones obtenidas
solucionesSinRepetir = encontrarSolucionesSinRepetir(soluciones)
mostrarSoluciones(solucionesSinRepetir)

Existe un total de  92  soluciones encontradas en la ejecución
*********************************************************************************
Esta es la solución  1
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]
*********************************************************************************
*********************************************************************************
Esta es la solución  2
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]
*********************************************************************************
*********************************************************************************
Esta es la solución  3
[[0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]